### ISSUE TITLE
bug(naijatype): custom CSS is too broad and impacts sites badly

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#3039]
The `naijatype` keyboard has the following in its associated CSS:

```css
body {
    background: rgb(193, 194, 193);
    font-family: "Andika","DejaVu Sans","AndikaAfr","Andika Afr","Andika New Basic Compact";
}
```

https://github.com/keymanapp/keyboards/blob/03b932e9b9558b6885534d31934084d00e88a6ef/experimental/n/naijatype/source/naijatype.css#L6-L9

_Originally posted by @jahorton in https://github.com/keymanapp/help.keyman.com/issues/1272#issuecomment-2298050379_

The CSS rules need to be restricted to the keyboard elements. 

(Note, a future update of KeymanWeb may use 'shadow dom' to prevent this kind of style leakage, see keymanapp/keyman#4881)
